site_name: Веб-программирование. Авдиенко Данила. K 3340

theme:
  name: material
  language: ru

nav:
  - Главная: index.md
  - ЛР1:
      - Отчёт: lr1/report.md
      
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences